contact_links:
  - name: Discord server
    url: https://discord.gg/pQnH4J3
    about: Please ask and answer questions about mods here.
  - name: Goose Support for Windows
    url: https://discord.gg/B5sUeDC
    about: Do you have support questions about Goose on Windows? Please ask here.
  - name: Goose Support for Mac
    url: https://discord.gg/JYHjWVA
    about: Do you have support questions about Goose on Mac? Please ask here.
